### ISSUE TITLE
add items to water strainer

### ISSUE THREAD

**Issue by mando222** [mando222/tradecraft#11]

**Comment by ilKestrelHawkli** [comment]
What if we added EnderIO infinity essence (normally have to set bedrock on fire, not easily automated)?

**Comment by mando222** [comment]
config/waterstrainer/waterstrainer_loottables.cfg

**Comment by mando222** [comment]
added the item but need to test

**Comment by ilKestrelHawkli** [comment]
Test confirmed, lets keep this open in case we want to add more

**Comment by mando222** [comment]
closed for now
