### ISSUE TITLE
Ender IO item/fluid/power transport should require immersive item/fluid/power transport to craft

### ISSUE THREAD

**Issue by mando222** [mando222/tradecraft#14]

**Comment by ilKestrelHawkli** [comment]
I've changed the recipe for Item conduit to require 3 IE conveyors and 6 Pulsating nuggets (previously was 6 conduit binder and 3 pulsating nuggets). I'm wondering if for power we should stick with IE (maybe keep the high tier enderIO conduit and make it more expensive).

**Comment by mando222** [comment]
Yeah I think eIO is to OP to be mid game but could be really nice late game.
