### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by ilKestrelHawkli** [mando222/tradecraft#19]
I've been having the pack balloon to over 9GB of memory usage.
I think we should pare down the ancillary mods.
I have disabled the following on my end as well has added some java args to optimize it down to ~5GB on startup.

-Vampirism
-Vampirism Integrations
-Howling Moon
-Historicized Medicine
-Millenaire
-Reptile Mod
-The Disenchanter Mod

**Comment by mando222** [comment]
We should remove CoralReefs as they don't look that good and will cause some overhead

**Comment by ilKestrelHawkli** [comment]
remove tiny progressions

**Comment by mando222** [comment]
others that we might want to remove:

[ ] Better Agriculture
blockcraftery
fast food
hopper Ducts
Landlust
logic 101
Nuclear Option
Redstone Flux
Rustic
Wither Skeleton Tweaks

**Comment by mando222** [comment]
closing but will need to revisit.
