### ISSUE TITLE
modularly install enderIO and Mek

### ISSUE THREAD

**Issue by mando222** [mando222/tradecraft#25]

**Comment by ilKestrelHawkli** [comment]
Thinking through this more, I think we should leave them as is (maybe get rid of Mek Gens and Tools) and gate Mekanism into late game, it has a lot of cool late game systems to quadruple ores with really complex automation. So, Immersive for early game, EnderIO for mid-game with dependencies on Immersive, and Mekanism for late-game with dependencies on EnderIO.

thoughts?
